### ISSUE TITLE
留言 - alittlebear's blog

### ISSUE THREAD

**Issue by a-little-bear** [a-little-bear/a-little-bear.github.io#10]
http://www.alittlebear.tk/message/ 

 <p><strong>来说点啥呗~</strong>  </p>

**Comment by 3388500075** [comment]
如果不是看评论，我还不知道有播放器

**Comment by a-little-bear** [comment]
> @3388500075
> 如果不是看评论，我还不知道有播放器

看到了看到了~~(●'◡'●)

**Comment by 3388500075** [comment]
咦，音乐自动播放了，加油，争取早日完善功能= =

**Comment by a-little-bear** [comment]
> @3388500075
> 咦，音乐自动播放了，加油，争取早日完善功能= =

改了好几个小时呢(T_T)

**Comment by a-little-bear** [comment]
> @3388500075
> 咦，音乐自动播放了，加油，争取早日完善功能= =

不会自动播放了，改回来了(●'◡'●)

**Comment by loadingfd** [comment]
推荐使用valine这个登录时真的烦

**Comment by a-little-bear** [comment]
> @loadingfd
> 推荐使用valine这个登录时真的烦

这是哪路大神。。说实话这个博客就是给自己看的。。。1没技术，2没好东西；而且碎碎念还有疫情已经发了那么多了，改了全没了。。

**Comment by 3388500075** [comment]
熊熊，为什么，你这里留言，我邮件会收到呀

**Comment by a-little-bear** [comment]
> @3388500075
> 熊熊，为什么，你这里留言，我邮件会收到呀

我也是，https://www.cnblogs.com/Scar007/p/8126329.html

**Comment by 2466949224** [comment]
想看飞卢小说咋整啊---

**Comment by a-little-bear** [comment]
> @2466949224
> 想看飞卢小说咋整啊---

我用爱看书吧，小说娃，等。。再加一个去广告（如Adguard），爽歪歪，无r18广告。
不过都是图片章节。
这里有一个论坛，里面都是付费的，不推荐。。http://www.93book.com/
